<h2>モデル</h2>
<h3>プロパティ</h3>
<table class="table">
<tr>
  <th>プロパティ名</th>
  <th>説明</th>
  <th>デフォルト値</th>
</tr>
<tr>
  <td>actor</td>
  <td>アクター</td>
  <td>$params['actor']</td>
</tr>
<tr>
  <td>table</td>
  <td>テーブル</td>
  <td>$params['class']</td>
</tr>
<tr>
  <td>alias</td>
  <td>エイリアス</td>
  <td>$params['alias']</td>
</tr>
<tr>
  <td>action</td>
  <td>アクション</td>
  <td>$params['method']</td>
</tr>
<tr>
  <td>parent_id</td>
  <td>親エンティティID</td>
  <td>$params['parent_id']</td>
</tr>
<tr>
  <td>session</td>
  <td>indexのセッション</td>
  <td>isset($params['session']) ? $params['session'] : []</td>
</tr>
<tr>
  <td>primary_key</td>
  <td>主キー</td>
  <td>"{$this->table}_id"</td>
</tr>
<tr>
  <td>has_hash</td>
  <td>1:nアソシエーション</td>
  <td>[]</td>
</tr>
<tr>
  <td>action_hash</td>
  <td>CRUDアクション</td>
  <td>['index', 'view', 'add', 'edit', 'delete']</td>
</tr>
<tr>
  <td>select_hash</td>
  <td>SELECT列</td>
  <td>["{$this->table}_id" => NULL, "{$this->table}_name" => NULL]</td>
</tr>
<tr>
  <td>join_hash</td>
  <td>LEFT JOIN</td>
  <td>[]</td>
</tr>
<tr>
  <td>set_list</td>
  <td>INSERT/UPDATE列</td>
  <td>["{$this->table}_name"]</td>
</tr>
<tr>
  <td>fixed_hash</td>
  <td>INSERETでの固定値</td>
  <td>[]</td>
</tr>
<tr>
  <td>where_list</td>
  <td>固定のWHERE</td>
  <td>[]</td>
</tr>
<tr>
  <td>where_hash</td>
  <td>POSTによるWHERE</td>
  <td>[]</td>
</tr>
<tr>
  <td>order_by_hash</td>
  <td>ORDER BY選択肢</td>
  <td>["{$this->primary_key}_asc" => "{$this-&gt;primary_key} ASC", "{$this->primary_key}_desc" => "{$this-&gt;primary_key} DESC"]</td>
</tr>
<tr>
  <td>limit_list</td>
  <td>LIMIT選択肢</td>
  <td>[10]</td>
</tr>
<tr>
  <td>display</td>
  <td>ヘッダなどに使用するフィールド</td>
  <td>"{$this->table}_name"</td>
</tr>
<tr>
  <td>hidden_list</td>
  <td>取得するが表示しない</td>
  <td>[$this->primary_key]</td>
</tr>
<tr>
  <td>use_card</td>
  <td>一覧をカード形式で表示する</td>
  <td>FALSE</td>
</tr>
</table>
